name: metric
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cudatoolkit=11.1.1=h6406543_8
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - ilmbase=2.5.5=h780b84a_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.1.0=h2733197_1
  - libuv=1.42.0=h7f98852_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.2.0=py38hab2c0dc_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openexr=2.5.5=hf817b99_0
  - openexr-python=1.3.2=py38hc7cd18a_2
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - readline=8.1.2=h7f8727e_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cu111
  - typing_extensions=4.0.1=pyha770c72_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - cycler==0.11.0
    - fonttools==4.28.5
    - imageio==2.13.5
    - imageio-ffmpeg==0.4.5
    - kiwisolver==1.3.2
    - lpips==0.1.4
    - matplotlib==3.5.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pillow==9.0.0
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - scipy==1.7.3
    - tqdm==4.62.3
prefix: /home/cgv839/anaconda3/envs/metric
