name: jax
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_1
  - ilmbase=2.5.5=h780b84a_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openexr=2.5.5=hf817b99_0
  - openexr-python=1.3.2=py38hc7cd18a_2
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - chex==0.1.0
    - cycler==0.11.0
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - flax==0.3.6
    - fonttools==4.33.3
    - gast==0.3.3
    - gin-config==0.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.41.1
    - h5py==2.10.0
    - idna==3.3
    - imageio==2.13.0
    - imageio-ffmpeg==0.4.5
    - jax==0.2.22
    - jaxlib==0.1.72+cuda111
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==12.0.0
    - markdown==3.3.4
    - matplotlib==3.5.2
    - msgpack==1.0.2
    - numpy==1.18.5
    - oauthlib==3.1.1
    - opencv-python==4.5.4.58
    - opt-einsum==3.3.0
    - optax==0.1.0
    - packaging==21.3
    - pillow==8.4.0
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymcubes==0.1.2
    - pyparsing==3.0.6
    - pysdf==0.1.8
    - python-dateutil==2.8.2
    - pyyaml==5.3.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - rtree==0.9.7
    - scipy==1.7.2
    - six==1.16.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - termcolor==1.1.0
    - toolz==0.11.2
    - tqdm==4.62.3
    - trimesh==3.9.35
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
prefix: /home/cgv839/anaconda3/envs/jax
